# Generated by Django 4.2.1 on 2023-05-09 05:09

from django.db import migrations
import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_seller_customuser_is_seller_userprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
