# Generated by Django 4.2.1 on 2023-05-20 16:10

from django.db import migrations
import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.managers.CustomUserManager()),
                ("users", users.managers.UserManager()),
                ("sellers", users.managers.SellerManager()),
            ],
        ),
    ]
