# Generated by Django 4.2.1 on 2023-05-09 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
    ]
