# Generated by Django 4.2.1 on 2023-05-11 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Auth User", "verbose_name_plural": "Auth Users"},
        ),
        migrations.DeleteModel(
            name="SellerProfile",
        ),
    ]
