# Generated by Django 4.2.1 on 2023-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
    ]
