# Generated by Django 4.2.1 on 2023-05-15 18:18

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="user_profile_pictures"
            ),
        ),
    ]
