# Generated by Django 4.2.1 on 2023-05-11 03:43

from django.db import migrations, models
import django.db.models.deletion
import sellers.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0006_remove_sellerprofile_user_delete_seller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", sellers.managers.SellerManager()),
            ],
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
                    ),
                ),
            ],
        ),
    ]
