# Generated by Django 4.2.1 on 2023-05-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sellers", "0002_alter_sellerprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
