# Generated by Django 4.2.1 on 2023-05-15 18:17

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0003_alter_sellerprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="profile_picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="seller_profile_pictures"
            ),
        ),
    ]
