# Generated by Django 4.2.1 on 2023-05-18 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetfile",
            name="file",
            field=models.FileField(
                upload_to="media_assets/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp", "mp4"],
                        message="Only PNG, JPG, JPEG, WEBP, and MP4 files are allowed.",
                    )
                ],
            ),
        ),
    ]
