# Generated by Django 4.2.1 on 2023-05-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_assets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="users.sellerprofile",
            ),
        ),
        migrations.AddField(
            model_name="assetfile",
            name="media_asset",
            field=models.ManyToManyField(
                related_name="files", to="media_assets.mediaasset"
            ),
        ),
        migrations.AddField(
            model_name="assetfile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_files",
                to="users.sellerprofile",
            ),
        ),
    ]
