# Generated by Django 4.2.1 on 2023-05-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_managers"),
        ("media_assets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetfile",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_files",
                to="users.sellerprofile",
            ),
            preserve_default=False,
        ),
    ]
