# Generated by Django 4.2.1 on 2023-05-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_alter_country_options_country_zipcode_regex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
