# Generated by Django 4.2.1 on 2023-05-30 14:46

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_alter_address_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="state",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="country",
                chained_model_field="country",
                limit_choices_to={"country__isnull": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="address.state",
            ),
        ),
    ]
