# Generated by Django 4.2.1 on 2023-05-14 16:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_userprofile_address"),
        ("address", "0004_alter_country_zipcode_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="user_profile",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="users.userprofile",
            ),
            preserve_default=False,
        ),
    ]
