# Generated by Django 4.2.1 on 2023-05-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("address", "0005_address_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="address",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="object_id",
            field=models.PositiveIntegerField(default="1"),
            preserve_default=False,
        ),
    ]
