# Generated by Django 4.2.1 on 2023-05-18 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="product_inventory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="product_attribute",
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalues",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productattributevalues",
            name="attributevalues",
        ),
        migrations.RemoveField(
            model_name="productattributevalues",
            name="productinventory",
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="attribute_values",
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="product_type_attributes",
        ),
        migrations.AlterUniqueTogether(
            name="producttypeattribute",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="producttypeattribute",
            name="product_attribute",
        ),
        migrations.RemoveField(
            model_name="producttypeattribute",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product_inventory",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
        migrations.DeleteModel(
            name="Media",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
        migrations.DeleteModel(
            name="ProductAttributeValues",
        ),
        migrations.DeleteModel(
            name="ProductInventory",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="ProductTypeAttribute",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
