# Generated by Django 4.2.1 on 2023-05-20 16:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-05-20 16:10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
