# Generated by Django 4.2.1 on 2023-05-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0004_sellerprofile_profile_picture"),
        ("products", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellers.sellerprofile",
            ),
            preserve_default=False,
        ),
    ]
