# Generated by Django 4.2.1 on 2023-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productvariant_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="name",
            field=models.CharField(default="RED-L", max_length=255),
            preserve_default=False,
        ),
    ]
