# Generated by Django 4.2.1 on 2023-05-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productvariant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
