# Generated by Django 4.2.1 on 2023-05-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0004_sellerprofile_profile_picture"),
        ("products", "0007_productvariant_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="sellers.sellerprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="owner",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attribute_values",
                to="sellers.sellerprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variants",
                to="sellers.sellerprofile",
            ),
            preserve_default=False,
        ),
    ]
